
release-pypi:
  image: python:3.7
  only:
    - /^version-.*$/
  script:
    - pip install -U twine
    - python setup.py sdist
    - twine upload dist/*

update-wiki:
#  only:
#    - master
  script:
    - content=$(cat README.md)
    - curl -H "JOB_TOKEN:${CI_JOB_TOKEN}" -H "Content-Type:application/json" -X PUT \
           "https://gitlab.com/api/v4/projects/${CI_PROJECT_ID}/wikis/home" \
           -d "{\"content\":\"${content}\"}"
