version: 2
jobs:
  automated-tests:
    docker:
      - image: colibris/tox
    steps:
      - checkout
      - run: tox --workdir=/tmp/tox --recreate

  release-pypi:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run: |
          virtualenv project
          source project/bin/activate
          pip install -U twine virtualenv
          python setup.py sdist
          twine upload dist/*

workflows:
  version: 2
  tests:
    jobs:
      - automated-tests

  release:
    jobs:
      - release-pypi:
          context: colibris-global
          filters:
            tags:
              only: /^version-.*$/
            branches:
              ignore: /.*/
